name: CI
on: push
env:
  GO_VERSION: '1.20'
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Print info about environment
        run: go version
      - name: Install dependencies
        run: source ./run.sh && run::install
      - name: Run unit tests
        run: source ./run.sh && run::test
